# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqYdt9PzDREjjw9S3MRvxclz3hqyn4h_
"""

import zipfile

with zipfile.ZipFile("novatech_dataset_part1.zip", "r") as zip_ref:
    zip_ref.extractall("data")

import os

print(os.listdir("data"))

with open("data/company_profile.txt", "r", encoding="utf-8") as f:
    print(f.read())

!pip install -q chromadb sentence-transformers langchain pypdf

import os

documents = []

for filename in os.listdir("data"):
    if filename.endswith(".txt"):
        with open(os.path.join("data", filename), "r", encoding="utf-8") as f:
            documents.append({
                "filename": filename,
                "content": f.read()
            })

print(f"Loaded {len(documents)} documents")

print(documents[0]["filename"])
print(documents[0]["content"][:300])

!pip install -q chromadb sentence-transformers langchain langchain-community

import os

documents = []

for filename in os.listdir("data"):
    if filename.endswith(".txt"):
        with open(os.path.join("data", filename), "r", encoding="utf-8") as f:
            documents.append({
                "source": filename,
                "text": f.read()
            })

print(f"Loaded {len(documents)} documents")

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

chunks = []

for doc in documents:
    split_text = splitter.split_text(doc["text"])

    for chunk in split_text:
        chunks.append({
            "source": doc["source"],
            "text": chunk
        })

print("Total Chunks:", len(chunks))

print(chunks[0])

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

texts = [chunk["text"] for chunk in chunks]

embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True
)

print("Embeddings Shape:", embeddings.shape)

import chromadb

client = chromadb.Client()

collection = client.create_collection(
    name="customer_support"
)

for i, chunk in enumerate(chunks):
    collection.add(
        ids=[str(i)],
        documents=[chunk["text"]],
        metadatas=[{"source": chunk["source"]}],
        embeddings=[embeddings[i].tolist()]
    )

print("Stored all chunks in ChromaDB!")

query = "What is your refund policy?"

query_embedding = embedding_model.encode(query).tolist()

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=3
)

for i, doc in enumerate(results["documents"][0]):
    print(f"\nResult {i+1}")
    print(doc)

!pip install -q google-generativeai

import google.generativeai as genai

genai.configure(api_key="YOUR_API_KEY")

model = genai.GenerativeModel("gemini-2.5-flash")

"""### Securely Storing and Accessing API Keys in Colab

To avoid hardcoding your API key directly in your notebook, which is a security risk, you can use Colab's built-in **Secrets Manager**.

1.  **Open Secrets Manager**: Click on the "🔑" (key) icon in the left sidebar of your Colab notebook.
2.  **Add a new secret**: Click "+ New secret" and add your API key. It's recommended to name it `GOOGLE_API_KEY` for consistency with common practices.
3.  **Enable notebook access**: Make sure the toggle next to your secret is enabled for your notebook to access it.

Now, you can access your API key in your code like this:

After updating the API key in Secrets Manager and running the above cell, the previous `BadRequest` error should be resolved, and you can proceed with generating content using the `model`.
"""

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=3
)

context = "\n\n".join(results["documents"][0])

print(context)

prompt = f"""
You are a professional customer service assistant for NovaTech Electronics.

Answer ONLY using the provided context.

If the answer is not available in the context, reply:

"I couldn't find that information in the company knowledge base."

Context:
{context}

Question:
{query}
"""

!pip install -q openai

from openai import OpenAI

client = OpenAI(
    api_key="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",
    base_url="https://api.groq.com/openai/v1"
)

client = OpenAI(
    api_key="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",
    base_url="https://api.groq.com/openai/v1"
)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": "Say hello in one sentence."
        }
    ]
)

print(response.choices[0].message.content)

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print(collection.count())

query = "What is your refund policy?"

query_embedding = embedding_model.encode(query).tolist()

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=3
)

context = "\n\n".join(results["documents"][0])

print(context)

prompt = f"""
You are NovaTech Electronics' AI Customer Service Assistant.

Answer ONLY using the context below.

If the answer is not in the context, say:
"I couldn't find that information in the company knowledge base."

Context:
{context}

Question:
{query}
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": "You are a helpful customer support assistant."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]
)

print(response.choices[0].message.content)

while True:
    query = input("\nAsk your question (type 'exit' to quit): ")

    if query.lower() == "exit":
        print("Thank you for using NovaTech Customer Support!")
        break

    # Convert the question into an embedding
    query_embedding = embedding_model.encode(query).tolist()

    # Retrieve relevant chunks
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )

    # Build context
    context = "\n\n".join(results["documents"][0])

    # Create prompt
    prompt = f"""
You are NovaTech Electronics' AI Customer Service Assistant.

Answer ONLY using the provided context.

If the answer is not found in the context, reply:
"I couldn't find that information in the company knowledge base."

Context:
{context}

Question:
{query}
"""

    # Generate response
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You are a helpful customer support assistant."
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    print("\nAnswer:")
    print(response.choices[0].message.content)

    print("\nRetrieved Sources:")
    for metadata in results["metadatas"][0]:
        print("-", metadata["source"])

